// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/13/2025, 3:05:39 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/ToQa/portfolio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/ToQa/portfolio/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/ToQa/portfolio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/ToQa/portfolio/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/ToQa/portfolio/app/plugins/**/*.{js,ts,mjs}","E:/ToQa/portfolio/app/composables/**/*.{js,ts,mjs}","E:/ToQa/portfolio/app/utils/**/*.{js,ts,mjs}","E:/ToQa/portfolio/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/ToQa/portfolio/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/ToQa/portfolio/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/ToQa/portfolio/app/app.config.{js,ts,mjs}","E:/ToQa/portfolio/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;